services:
  test-db:
    image: postgres:14
    container_name: user-integration-test
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_test
