version: '3'
services:
  auth-frontend:
    image: hicsail/auth-client:main
    restart: always
    ports:
      - 3002:80
    env_file:
      - ../stack.env
  auth-admin:
    image: hicsail/auth-admin-client:main
    restart: always
    ports:
      - 3004:80
    env_file:
      - ../stack.env
  auth-backend:
    image: hicsail/auth-server:main
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ../stack.env
  auth-postgres:
    image: postgres:13
    container_name: auth-postgres-staging
    restart: always
    volumes:
      - auth-staging:/var/lib/postgresql/data
    env_file:
      - ../stack.env
  backup:
    image: offen/docker-volume-backup:v2.27.0
    restart: always
    env_file:
      - ../backup.env
      - ../stack.env
    volumes:
      - auth-staging:/backup:ro
volumes:
  auth-staging: ~
