version: '3'
services:
  auth-frontend:
    container_name: auth-client
    image: hicsail/auth-client:latest
    restart: always
    ports:
      - 3002:80
    env_file:
      - ../stack.env
  auth-admin:
    container_name: auth-admin
    image: hicsail/auth-admin-client:latest
    restart: always
    ports:
      - 3004:80
    env_file:
      - ../stack.env
  auth-backend:
    container_name: auth-server
    image: hicsail/auth-server:latest
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ../stack.env
  auth-postgres:
    image: postgres:13
    container_name: auth-postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      - auth-production:/var/lib/postgresql/data
    env_file:
      - ../stack.env
volumes:
  auth-production: ~
