version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    container_name: integration-test
    ports:
      - 5432:5432
    env_file:
      - .env.test
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
