name: client
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Up
        run: rm ../../package.json
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run prettier
      - name: Build
        run: npm run build
      - name: Verify Docker Image
        uses: docker/build-push-action@v3
        if: github.ref != 'refs/heads/main'
        with:
          context: ./packages/client
          push: false
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Build
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          context: ./packages/client
          push: true
          tags: hicsail/auth-client:unstable
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK_CLIENT }}
          preventFailureOnNoResponse: true
