name: common
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Up
        run: rm ../../package.json
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run prettier
      - name: Build
        run: npm run build
